// EngManAngular/src/app/messages-component/messages-component.component.ts
import { Component, OnInit } from '@angular/core';
import * as M from 'materialize-css';
import { UserViewModel, MessageModel, ReturnMessageModel } from '../app.models';
import { ApiService } from '../api.service';
import { MessagesService } from '../messages.service';

@Component({
  selector: 'app-messages-component',
  templateUrl: './messages-component.component.html'
})
export class MessagesComponentComponent implements OnInit {

  private Users: UserViewModel[] = [];
  private ChoosenUser: string = `Main`;
  private Message = "";


  constructor(private apiService: ApiService
    , private messagesService: MessagesService)
  {

  }

  public ngOnInit(): void
  {
    document.addEventListener('DOMContentLoaded', function() {
      let elems = document.querySelectorAll('.modal');
      let instances = M.Modal.init(elems, {});
    });
  }

  private UpdateUser(): void
  {
    this.messagesService.Messages = [];
    let doc:any = document.getElementById("selectUser");
    if(doc.options[doc.selectedIndex].text == "Main")
    {
      this.ChoosenUser = "Main";
      return;
    }
    this.UpdateMessages(doc.options[doc.selectedIndex].text);
  }

  UpdateMessages(email: string): void
  {
    let doc:any = document.getElementById("selectUser");
    doc.value = email;
    this.ChoosenUser = email;
    this.messagesService.GetMessages(this.FindUserByEmail(email).Id, 0);
    this.Message = "";
  }

  private OpenMessages(): void
  {
    this.Users = [];
    this.apiService
    .GetAllUsers()
    .subscribe(
      obj => 
      {
        for(let i = 0; i < obj.length; i++)
        {
          if(obj[i].Id != this.apiService.UserId)
          {
            this.Users.push(obj[i]);
          }
        }
      },
      error => console.log(error)
    )
    this.messagesService.Messages = [];
    this.messagesService.GetNewMessages();
    document.getElementById("message-icon").className = "medium material-icons";
    let doc:any = document.getElementById("selectUser");
    doc.value = "Main";
    this.ChoosenUser = "Main";
    this.Message = "";
  }

  private Send(): void
  {
    let date = new Date(Date.now());
    let hours = date.getHours() < 10 ? "0"+date.getHours() : date.getHours();
    let minutes = date.getMinutes() < 10 ? "0"+date.getMinutes() : date.getMinutes();
    let seconds = date.getSeconds() < 10 ? "0"+date.getSeconds() : date.getSeconds();
    let month = (date.getMonth()+1) < 10 ? "0"+(date.getMonth()+1) : (date.getMonth()+1);
    let day = date.getDate() < 10 ? "0"+date.getDate() : date.getDate();

    let mes = new MessageModel();
    mes.MessageId = 0;
    mes.SenderId = this.apiService.UserId;
    mes.BeneficiaryId = this.FindUserByEmail(this.ChoosenUser).Id;
    mes.Text = this.Message;
    mes.Time =  date.getFullYear() + "-" + month + "-" + day + "T" + hours + ":" + minutes + ":" + seconds + "+03:00";
    mes.CheckReadMes = false;
    this.messagesService.SendMessage(mes);
    this.Message = ``;
  }

  private Delete(mes: ReturnMessageModel): void
  {
    this.messagesService.DeleteMessages(mes);
  }

  private DownloadMore(): void
  {
    this.messagesService.GetMessages(this.FindUserByEmail(this.ChoosenUser).Id, this.messagesService.Messages[this.messagesService.Messages.length - 1].MessageId);
  }

  private FindUserByEmail(email: string): UserViewModel
  {
    return this.Users[this.Users.findIndex((user) => user.Email === email)];
  }

}

<p style="position: fixed; right:25px; bottom: 25px">
  <a class="modal-trigger" style="color:darkred" href="#modal1" (click)="OpenMessages()"><i id="message-icon" class="medium material-icons">email</i></a>
</p>

<div id="modal1" class="modal bottom-sheet modal-fixed-footer" style="width: 500px; right: 0; left: auto">
    <div class="modal-content">
      <label>Choose user</label>  
      <select id="selectUser" class="browser-default" (change)="UpdateUser()">
          <option value="" selected>Main</option>
          <option *ngFor="let user of Users">{{user.Email}}</option>
      </select>
      <div *ngIf="ChoosenUser!='Main'" style="padding-bottom:25px">
        <div class="row" *ngFor="let message of messagesService.Messages">
          <blockquote class="text left" *ngIf="message.Sender.Id != apiService.UserId">
            <h6>{{message.Sender.FirstName}} {{message.Time | date:"HH:mm yyyy-MM-dd"}} <a style="cursor:pointer;" (click)="Delete(message)">delete</a></h6>
            <span>{{message.Text}}</span>
          </blockquote>
          <blockquote class="text right" *ngIf="message.Sender.Id == apiService.UserId">
              <h6><a style="cursor:pointer;" (click)="Delete(message)">delete</a> {{message.Time | date:"HH:mm yyyy-MM-dd"}} You</h6>
              <span>{{message.Text}}</span>
          </blockquote>
        </div>
        <div class="row center"><a *ngIf="messagesService.Messages.length > 0 && messagesService.Messages.length % 100 == 0" style="cursor:pointer;" (click)="DownloadMore()">more...</a></div>
      </div>
      <div *ngIf="ChoosenUser=='Main'" style="padding-bottom:25px">
          <div class="row" *ngFor="let message of messagesService.NewMessages">
            <blockquote class="text left" *ngIf="message.Sender.Id != apiService.UserId">
              <span style="cursor:pointer" (click)="UpdateMessages(message.Sender.Email)">{{message.Sender.FirstName + " " + message.Sender.LastName}}</span>
            </blockquote>
          </div>
        </div>
    </div>
    <div class="modal-footer" style="height: 113px;">
      <div class="row">
          <div class="input-field col s10">
              <textarea id="icon_prefix2" class="materialize-textarea" [disabled]="ChoosenUser == 'Main'" [(ngModel)]="Message" (keyup.enter)="Send()"></textarea>
              <label for="icon_prefix2">Message</label>
          </div>
          <a class="btn" style="margin-top: 20px" [class.disabled]="ChoosenUser == 'Main'" (click)="Send()">send</a>
      </div>
    </div>
</div>

// EngManVue/src/components/Messages.vue
<template>
<div>
  <div class="loading" v-if = "inProgress">Loading&#8230;</div>
  <div id = "messages-view" class = 'messages-view'>
      <div class = "label-form-mes">
            <span>Chat</span>
            <span style = "float: right; font-size:10px; cursor: pointer" v-on:click = "closeform(); clickCloseButton = true;"><img title="Close" style = "width: 20px; height: auto" type = "img" src = "../assets/close-icon.png"></span>
      </div>
      <input :disabled = "chooseUser" v-bind:class = "{'messages-input-choosen': chooseUser}" placeholder="Search..." type="text" class = "select-form-mes" list="users_emails" v-model = "beneficiaryEmail" v-on:change = "changeBeneficiary(beneficiaryEmail)"/>
      <span v-if = "chooseUser" style = "float: left; font-size:10px; cursor: pointer" v-on:click = "activeInputChooseUser"><img title="Return to user selection" style = "width: 20px; height: auto" type = "img" src = "../assets/arrow-up.png"></span>
      <datalist id = "users_emails">
            <option v-for = "user in users" v-if = "user.Id != $store.state.user.Id" :key = "user.Id">
                {{user.Email}}
            </option>
      </datalist>
      <div v-if = "beneficiary == undefined && beneficiaryEmail == ''" class = "new-mess-users-list" style = "height: 330px;">
          <div v-for = "el in sortednewmessages" :key = "el.MessageId" class = "message-beneficiary pointer" style = "white-space: nowrap;text-overflow: ellipsis;overflow: hidden;" v-on:click = "beneficiaryEmail = el.Sender.Email;changeBeneficiary(beneficiaryEmail)">
            {{el.Sender.FirstName}}: {{el.Text}}
          </div>
      </div>
      <div v-else class = "messages">
          <div v-for = "el in sortedmessages" :key = "el.MessageId">
              <div v-if = "el.Sender.Id == sender.Id" class = "label-sender"><span style = "font-size: 10px; cursor: pointer" v-on:click = "deleteMessage(el.MessageId)">delete</span> <span style = "font-size: 10px">{{dateTime(el.Time)}}</span> You</div>
              <div v-if = "el.Sender.Id == sender.Id" class = "message-sender">
                  {{el.Text}}
              </div>
              <div v-if = "el.Sender.Id != sender.Id" class = "label-beneficiary">{{el.Sender.FirstName}} <span style = "font-size: 10px">{{dateTime(el.Time)}}</span> <span style = "font-size: 10px; cursor: pointer" v-on:click = "deleteMessage(el.MessageId)">delete</span></div>
              <div v-if = "el.Sender.Id != sender.Id" class = "message-beneficiary">
                  {{el.Text}}
              </div>
          </div>
      </div>
      <div v-if = "chooseUser" class = "input-form-mes" v-on:keyup.enter="sendMessage()">
            <textarea placeholder = "Type a message" class = "textarea-mes" type = "text" v-model = "message" :disabled = "beneficiaryEmail == ''"/>
            <span style = "float: right; font-size: 10px; cursor: pointer; margin-right: 25px;" v-on:click = "sendMessage();"><img title="Send" style = "width: 30px; height: auto" type = "img" src = "../assets/send-icon.png"></span>
      </div>
  </div>
</div>
</template>

<script>
import api from '../api/api'

export default {
  name: 'messages-view',
  data: () => {
      return {
          chooseUser: false,
          clickCloseButton: false,
          clickAtForm: false,
          inProgress: false,
          message: '',
          beneficiary: undefined,
          beneficiaryEmail: '',
          sender: ''
      }
  },
  methods: {
      activeInputChooseUser(){
          this.chooseUser = false;
          this.beneficiary = undefined;
          this.beneficiaryEmail = '';
      },
      closeform(){
          this.inProgress = false;
          this.message = '';
          this.beneficiary = undefined;
          this.beneficiaryEmail = 'none';
          this.sender = '';
          this.$emit('closeMessages');
      },
      deleteMessage(id){
          if(this.inProgress) return;
          this.inProgress = true;
          if(confirm("Are you sure you want to delete the message?") == true){
            api.deleteMessage(id)
            .then(result =>{
                if(result === "Delete completed successful")
                {
                    this.$store.dispatch('getMessages');
                    this.inProgress = false;
                }
                else
                {
                    if(result.response)
                    {
                        if(result.response.data.Message)
                        {
                            this.inProgress = false;
                            console.log(result.response.data.Message);
                            return;
                        }
                    }
                    console.log('Bad request 400');
                    this.inProgress = false;
                }
            })
            .catch(e => {
                console.log(e);
                this.inProgress = false;
            })
          } else{
              alert("You canceled the deletion!");
              this.inProgress = false;
          }
      },
      changeBeneficiary(email){
          if(this.inProgress) return;
          this.inProgress = true;
          this.message = '';
          this.chooseUser = false;
          if(this.beneficiaryEmail == ''){
               this.beneficiary = undefined;
               this.inProgress = false;
               return;
          }
          this.beneficiary = this.$store.getters.users.filter(function(user){
              return user.Email == email;
          })[0];
          if(this.$store.state.newmess)
          {
            for(var i = 0; i < this.sortedmessages.length; i++)
            {
                if(!this.sortedmessages[i].CheckReadMes)
                {
                    api.ReadMessages(this.sortedmessages.map(function(item){
                        return {
                            MessageId: item.MessageId,
                            SenderId: item.Sender.Id,
                            BeneficiaryId: item.Beneficiary.Id,
                            Text: item.Text,
                            Time: item.Time,
                            CheckReadMes: item.CheckReadMes
                        }
                    }))
                    .then(res => {
                        this.inProgress = false;
                        if(res != undefined)
                        {
                            if(res.length > 0)
                            {
                                this.$store.dispatch('getMessages');
                            }
                            else
                            {
                                if(res.response)
                                {
                                    if(res.response.data.Message)
                                    {
                                        this.inProgress = false;
                                        console.log(res.response.data.Message);
                                        return;
                                    }
                                }
                                console.log('Bad request 400');
                                this.inProgress = false;
                            }
                        }
                    })
                    .catch(e => {
                        console.log(e);
                        this.inProgress = false;
                    })
                }
            }
            this.inProgress = false;
          }
          else{
            this.inProgress = false;
          }
          this.chooseUser = true;
      },
      sendMessage(){
          if(this.inProgress) return;
          this.inProgress = true;
          if(this.beneficiary != undefined)
          {
            if(this.message != '')
            {
                var date = new Date(Date.now());
                var hours = date.getHours() < 10 ? "0"+date.getHours() : date.getHours();
                var minutes = date.getMinutes() < 10 ? "0"+date.getMinutes() : date.getMinutes();
                var seconds = date.getSeconds() < 10 ? "0"+date.getSeconds() : date.getSeconds();
                var month = (date.getMonth()+1) < 10 ? "0"+(date.getMonth()+1) : (date.getMonth()+1);
                var day = date.getDate() < 10 ? "0"+date.getDate() : date.getDate();
                api.sendMessage({
                    MessageId: 0,
                    SenderId: this.sender.Id,
                    BeneficiaryId: this.beneficiary.Id,
                    Text: this.message,
                    Time: date.getFullYear() + "-" + month + "-" + day + "T" + hours + ":" + minutes + ":" + seconds + "+03:00",
                    CheckReadMes: 0
                })
                .then(res => 
                {
                    if(res === true)
                    {
                        var proxy = this.$store.state.connectionSignalR.createHubProxy('chat');
                        proxy.invoke("Send", {
                            MessageId: 0,
                            SenderId: this.sender.Id,
                            BeneficiaryId: this.beneficiary.Id,
                            Text: this.message,
                            Time: date.getFullYear() + "-" + month + "-" + day + "T" + hours + ":" + minutes + ":" + seconds + "+03:00",
                            CheckReadMes: 0
                        });
                        this.$store.dispatch('getMessages')
                    }
                    else
                    {
                        if(res.response)
                        {
                            if(res.response.data.Message)
                            {
                                this.inProgress = false;
                                console.log(res.response.data.Message);
                                return;
                            }
                        }
                    }
                })
                .catch(e =>
                {
                    console.log(e);
                    this.inProgress = false;
                })
            }   
          }
          this.message = '';
          this.inProgress = false;
      },
      dateTime(_date){
                var date = new Date(_date);
                var hours = date.getHours() < 10 ? "0"+date.getHours() : date.getHours();
                var minutes = date.getMinutes() < 10 ? "0"+date.getMinutes() : date.getMinutes();
                return date.getDate() + '.' + (date.getMonth()+1) + '.' + date.getFullYear() + ' ' + hours + ":" + minutes;
      }
  },
  computed: {
      users(){
          return this.$store.getters.users;
      },
      sortedmessages(){
          this.sender = this.$store.state.user;
          var vue = this;
          if(this.beneficiary != undefined && this.beneficiaryEmail != '')
          return this.$store.getters.messages.filter(function(mes){
              return mes.Beneficiary.Id == vue.beneficiary.Id || mes.Sender.Id == vue.beneficiary.Id
          });
      },
      sortednewmessages(){
          var newmess = [];
          for(var i = this.$store.state.newmessages.length-1; i >= 0; i--)
          {
              var contain = false;
              for(var k = 0; k < newmess.length; k++)
              {
                  if(newmess[k].Sender.Id == this.$store.state.newmessages[i].Sender.Id)
                  {
                      contain = true;
                  }
              }
              if(!contain)
              {
                  newmess.push(this.$store.state.newmessages[i]);
              }
          }
          return newmess;
      }
  },
  created(){
      this.$store.dispatch('getMessages');
      this.$store.dispatch('getUsers');
      this.sender = this.$store.state.user;
  },
  mounted(){
        document.getElementById('messages-view').addEventListener('click', clickAtForm, false);
        document.body.addEventListener('click', clickAtBody, false);
        var vue = this;
        function clickAtForm(event){
            vue.clickAtForm = true;
            if(vue.clickCloseButton)
            {
                document.body.removeEventListener('click', clickAtBody);
            }
        };
        function clickAtBody(event){
            if(!vue.clickAtForm){
                vue.clickAtForm = true;
                document.body.removeEventListener('click', clickAtBody);
                vue.$emit('closeMessages');
                vue.closeform();
                return;
            }
            vue.clickAtForm = false;
        };
  }
}
</script>
